### ISSUE TITLE
Local Setup Error 

### ISSUE THREAD

**Issue by DESHRAJ** [batra-mlp-lab/CloudCVfy-Frontend#3]
```
ubuntu@ip-10-0-0-41:~/deshraj/CloudCVfy-Frontend$ npm install 
npm WARN package.json Dependency 'react' exists in both dependencies and devDependencies, using 'react@15.1.0' from dependencies
npm WARN package.json Dependency 'rimraf' exists in both dependencies and devDependencies, using 'rimraf@^2.5.2' from dependencies
externalip@1.0.2 node_modules/externalip
└── superagent@0.18.2 (extend@1.2.1, qs@0.6.6, methods@1.0.1, component-emitter@1.1.2, cookiejar@2.0.1, reduce-component@1.0.1, mime@1.2.11, debug@1.0.4, readable-stream@1.0.27-1, formidable@1.0.14, form-data@0.1.3)
ubuntu@ip-10-0-0-41:~/deshraj/CloudCVfy-Frontend$ npm start -s 
Starting app in dev mode...

/home/ubuntu/deshraj/CloudCVfy-Frontend/node_modules/eslint-watch/src/eslint/cli.js:19
    fs.accessSync(eslintPath);
       ^
TypeError: Object #<Object> has no method 'accessSync'
    at loadEslintPath (/home/ubuntu/deshraj/CloudCVfy-Frontend/node_modules/eslint-watch/src/eslint/cli.js:19:8)
    at Object.<anonymous> (/home/ubuntu/deshraj/CloudCVfy-Frontend/node_modules/eslint-watch/src/eslint/cli.js:22:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/deshraj/CloudCVfy-Frontend/node_modules/eslint-watch/src/eslint/index.js:4:8)
    at Module._compile (module.js:456:26)
ERROR: lint:watch: None-Zero Exit(1);
ubuntu@ip-10-0-0-41:~/deshraj/CloudCVfy-Frontend$ 

```

This is the error that I am getting while trying to setup the project locally. @tocttou can you look into this ?

**Comment by tocttou** [comment]
This is most likely a mismatch of required nodejs version.

**Comment by tocttou** [comment]
Were you able to proceed with setup?

**Comment by tocttou** [comment]
Setup is working fine with node 5 and 6
https://travis-ci.org/batra-mlp-lab/CloudCVfy-Frontend/builds/146205556
